apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-kid
  labels:
    app: script-kid
spec:
  selector:
    matchLabels:
      app: script-kid
  template:
    metadata:
      labels:
        app: script-kid
    spec:
      volumes:
        - name: diagnostics
          emptyDir: {}
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: script-kid
          image: ghcr.io/tianvan/script-kid:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /tmp
              name: diagnostics
        - name: monitor
          image: mcr.microsoft.com/dotnet/monitor
          imagePullPolicy: Always
          ports:
            - containerPort: 52323
          volumeMounts:
            - mountPath: /tmp
              name: diagnostics
---
apiVersion: v1
kind: Service
metadata:
  name: script-kid
spec:
  selector:
    app: script-kid
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: script-kid
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: script-kid.tianvan.com
      http:
        paths:
          - backend:
              service:
                name: script-kid
                port:
                  number: 80
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - script-kid.tianvan.com
      secretName: script-kid-tls
