apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-kid
  labels:
    app: script-kid
spec:
  selector:
    matchLabels:
      app: script-kid
  template:
    metadata:
      labels:
        app: script-kid
    spec:
      volumes:
        - name: diag
          emptyDir: {}
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: script-kid
          image: ghcr.io/tianvan/script-kid:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: DOTNET_DiagnosticPorts
              value: /diagnostics/port.sock
          volumeMounts:
            - mountPath: /diag
              name: diag
        - name: monitor
          image: mcr.microsoft.com/dotnet/monitor
          imagePullPolicy: Always
          args: ["--no-auth"]
          env:
            - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
              value: Listen
            - name: DOTNETMONITOR_DiagnosticPort__EndpointName
              value: /diag/port.sock
            - name: DOTNETMONITOR_Storage__DumpTempFolder
              value: /diag/dumps
            - name: DOTNETMONITOR_Urls
              value: http://localhost:52323
          volumeMounts:
            - mountPath: /diag
              name: diag
---
apiVersion: v1
kind: Service
metadata:
  name: script-kid
spec:
  selector:
    app: script-kid
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: script-kid
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: script-kid.tianvan.com
      http:
        paths:
          - backend:
              service:
                name: script-kid
                port:
                  number: 80
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - script-kid.tianvan.com
      secretName: script-kid-tls
